name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  # Pastikan arsitektur sesuai dengan runner
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Pastikan requirements.txt berisi semua dependensi
      - name: Lint with flake8
        run: |
          flake8 .  # Sesuaikan dengan konfigurasi flake8 Anda
      - name: Test with pytest
        run: |
          pytest  # Sesuaikan dengan path tes Anda
